server:
  port: 9095

#Database connection
spring:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
     driverClassName: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@localhost:1521:orcl
     username: system
     password: manager
  
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
 
  mail:
    host: smtp.gmail.com
    port: 587
    username: bsaraswoti48@gmail.com
    password: behera@1512
    protocol: smtp
    properties:
      mail:
        smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls: 
          enable: true
        ssl:
          trust: smtp.gmail.com



